# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PlanForMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase' 
  pod 'Firebase/Auth'
  pod 'Firebase/Database' 
  pod 'GoogleSignIn'
  target 'PlanForMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlanForMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
